//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOSwithSwift
{
    using System;
    using System.Collections.Generic;
    
    public partial class WordsList
    {
        public int WordId { get; set; }
        public string WordString { get; set; }
        public string WordStringChar { get; set; }
    }
}
